# Generated by Django 2.1.2 on 2019-04-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkingHour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcount',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workform',
            name='is_accept',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workkinds',
            name='work_kind',
            field=models.IntegerField(),
        ),
    ]
