# Generated by Django 2.1.2 on 2019-04-12 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkingHour', '0002_auto_20190412_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formstream',
            old_name='handler_id',
            new_name='handler',
        ),
        migrations.RenameField(
            model_name='workcount',
            old_name='workForm_id',
            new_name='workForm',
        ),
        migrations.RenameField(
            model_name='workform',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='workform',
            old_name='user_id',
            new_name='user',
        ),
    ]
