# Generated by Django 2.2.1 on 2019-05-03 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkingHour', '0003_auto_20190412_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formstream',
            options={'verbose_name': '工作流', 'verbose_name_plural': '工作流'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterModelOptions(
            name='workcount',
            options={'verbose_name': '工作量', 'verbose_name_plural': '工作量'},
        ),
        migrations.AlterModelOptions(
            name='workform',
            options={'verbose_name': '工作表', 'verbose_name_plural': '工作表'},
        ),
        migrations.AlterModelOptions(
            name='workkinds',
            options={'verbose_name': '工作种类', 'verbose_name_plural': '工作种类'},
        ),
        migrations.AddField(
            model_name='workcount',
            name='user_id',
            field=models.CharField(default='', max_length=20, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=500, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='project',
            name='leader_id',
            field=models.CharField(max_length=20, verbose_name='项目领导ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='over_date',
            field=models.DateField(verbose_name='项目到期时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='项目ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_kind',
            field=models.CharField(max_length=20, verbose_name='项目类别'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=100, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='项目开始时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_leader_id',
            field=models.CharField(max_length=20, verbose_name='小队领导ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.CharField(max_length=100, verbose_name='用户账户'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(max_length=100, verbose_name='用户所属部门'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(verbose_name='用户等级'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, verbose_name='用户名字'),
        ),
        migrations.AlterField(
            model_name='workcount',
            name='count',
            field=models.IntegerField(verbose_name='工作数量'),
        ),
        migrations.AlterField(
            model_name='workcount',
            name='description',
            field=models.CharField(max_length=300, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='workcount',
            name='order',
            field=models.IntegerField(verbose_name='订单'),
        ),
        migrations.AlterField(
            model_name='workcount',
            name='update_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='workcount',
            name='workForm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkingHour.WorkForm', verbose_name='工作表ID（外键）'),
        ),
        migrations.AlterField(
            model_name='workcount',
            name='workkinds',
            field=models.CharField(max_length=50, verbose_name='工作类型'),
        ),
        migrations.AlterField(
            model_name='workform',
            name='create_time',
            field=models.DateTimeField(verbose_name='工作表创建时间'),
        ),
        migrations.AlterField(
            model_name='workform',
            name='fast_handle_time',
            field=models.DateTimeField(verbose_name='第一次处理时间'),
        ),
        migrations.AlterField(
            model_name='workform',
            name='handle_id',
            field=models.IntegerField(verbose_name='处理ID'),
        ),
        migrations.AlterField(
            model_name='workform',
            name='is_accept',
            field=models.IntegerField(default=1, verbose_name='是否接受'),
        ),
        migrations.AlterField(
            model_name='workform',
            name='modify_time',
            field=models.DateTimeField(verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='workform',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkingHour.Project', verbose_name='项目ID（外键）'),
        ),
        migrations.AlterField(
            model_name='workform',
            name='score',
            field=models.IntegerField(verbose_name='分数'),
        ),
        migrations.AlterField(
            model_name='workform',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WorkingHour.User', verbose_name='用户ID（外键）'),
        ),
        migrations.AlterField(
            model_name='workform',
            name='workForm_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='工作表ID'),
        ),
    ]
